- name: Install MySQL Package
    block:
    - name: Install mysql
      apt:
        #update_cache: true
        name: python3-pymysql, mysql-server
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: Install MariaDB Package
      yum:
        name: mariadb-server, mariadb-client
        state: present
      when: ansible_facts['os_family'] == "RedHat"
    - name: Starting MySQL Service
      service:
        name: mysql
        state: started
        enabled: yes
  - name: Create Wordpress Database
    mysql_db:
      login_unix_socket: "{{ mysql['socket'] }}"
      name: "{{ mysql['db'] }}"
      state: present
  - name: Create Wordpress User
    mysql_user:
      check_implicit_admin: yes
      login_unix_socket: "{{ mysql['socket'] }}"
      name: "{{ mysql['user'] }}"
      password: "{{ mysql['passwd'] }}"
      host: localhost
      priv: "{{ mysql['db'] }}.*:ALL,GRANT"
      state: present
  - name: Download Wordpress Source
      async: 300
      poll: 0
      register: wp_source_result
      get_url:
        url: "{{ wp['url'] }}"
        checksum: "{{ wp['sha1'] }}"
        dest: "{{ wp['source'] }}"
  - name: sync
    async_status:
      jid: "{{ wp_source_result.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 100


